### PR TITLE
Add jest support

### PR DESCRIPTION
**Pull request by nsfmc**
adds jest, babel-jest, gulp-jest and harmonize (to resolve an issue
with gulp-jest needing node to be run with --harmony)

### CODE REVIEW

**Comment by nsfmc** [comment]
hi there, i actually don't know if this is how you would have approached this (or if you're not cool with the implementation). in any case, feel free to cherry pick or close this pr if it's not your bag. i find the harmonize requirement bit a janky, if you know a better approach, i'd enjoy hearing it.

hope alls well.

**Comment by steida** [comment]
Awesome, thank you! I didn't had a time to check Jest yet. Looks good to me, except 4 tabs ;)
Just question, is gulp-jest required? I'm trying generally to use as less gulp wrapper as possible. They tend to sucks. For example, gulp(s) for webpack is pain in the ass. Can you elaborate configuration with plain jest? Does it handle watching well?

**Comment by dmnd** [comment]
I've used jest without gulp purely via npm and package.json [like this](https://github.com/babel/babel-jest#usage):

```json
{
  "scripts": {
    "test": "jest"
  },
  "jest": {
    "scriptPreprocessor": "<rootDir>/node_modules/babel-jest",
    "testFileExtensions": ["es6", "js"],
    "moduleFileExtensions": ["js", "json", "es6"]
  }
}
```

What do you mean by watching though @steida? Running tests when files are modified?

**Comment by steida** [comment]
As I see it, npm is for CI and gulp for development. Npm should call gulp, because I don't like writing scripts in string :-) It works only for super simple scenarions.

**Comment by steida** [comment]
I mean Jest own watching system if any.

**Comment by nsfmc** [comment]
> except 4 tabs ;)

ugh, sorry, a separate ios project uses tabs and i haven't updated my editor config go back to spaces as the default.

the gulp-jest wrapper isn't so crazy though, it doesn't feel too difficult to remove. i also used the same `package.json` config that @dmnd put up there which ships with babel-jest. I agree though that the gulp wrappers tend to be real hit or miss, in this case, it doesn't seem to add any real value and uses its own dependency of jest-cli and react tools which will be a bit fragile if it deviates from the main project's react and friends. i'll keep you posted. 

thanks both for your eyes.

**Comment by nsfmc** [comment]
hi there @steida , i updated the pr so it no longer requires gulp-jest and also so that `gulp jest` returns 0/1 on success/failure. i assume at some point, `npm test` will call that, but not until the other tests merge into this. also fixed the spacing nits. give it a whirl and let me know what you think. I'm happy to squash the commits or however you'd like to handle that. 

best,
--marcos

**Comment by steida** [comment]
You are so thoughtful, thank you again. Review it tomorrow, busy as hell right now. Just one note, can you pay attention to https://github.com/steida/este instead of this example? I happily port all changes from Este back to this repo, but steida/este should be the source of truth.

**Comment by nsfmc** [comment]
totally! i'll abandon this review and patch it onto este. sorry i've been a bit hazy myself, new baby and all that. i noticed a few style snafus this morning which i can only attribute to sleep deprivation :stuck_out_tongue_closed_eyes: 

hope all's well

**Comment by steida** [comment]
So I finally merged it and thank you again for your effort. As you can see, you did just small changes. Great work dude.

**Pull request closed without merging**
